on:
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'src/**'
      - 'docs/**'
  pull_request:
    branches:
      - main
      - 'release/**'
    paths:
      - 'src/**'
      - 'docs/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
      - name: Run tests
        run: npm test

